image: python:3.7

stages:
 - style-check
 - compile
 - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - pip install -U platformio
  - cd ./rover/Wall-E

check_style:
  stage: style-check
  script: "echo $WTF"

compile_teensy:
  stage: compile
  script: "platformio run -e teensy40 -d ."

# compile_uno:
#   stage: compile
#   script: "platformio run -e uno -d ."
#   allow_failure: true

unit_testing:
  stage: test
  script: "echo $REMOTE_SO_HARD"
  variables: {PLATFORMIO_CI_SRC: "."}
